language: node_js

node_js:
  - lts/*

before_script:
  - npm run setup
  - npm run build

script:
  - npm test

after_success:
  - git add .
  - git commit commit_message

  branches:
    only:
      - master
      - dev

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
