language: node_js

node_js:
  - lts/*

before_script:
  - npm run setup
  - npm run build

script:
  - npm test

after_success:
  - git add .
  - git commit commit_message

skip_cleanup: true

branches:
  only:
    - master
    - dev
